### ISSUE TITLE
client error: (403) Forbidden. Change in Gmail API?

### ISSUE THREAD

**Issue by arturochian** [jimhester/gmailr#11]
Hi @jimhester. I'm new in this package. I installed this package and explored their function, other function work well for me. However sending a message gave me an error.

I tried using this code

msg <-  mime() %>%
 from("arturob.chian2@gmail.com") %>%
 to("arturob.chian@gmail.com") %>%
 text_body("Please don't reject my package")

send_message(msg)

However this error message Error in send_message(msg) : client error: (403) Forbidden

It seems like this is a "new" (From Octubre 2014) error because Gmail's API changed.

http://stackoverflow.com/questions/26135310/gmail-api-returns-403-error-code-and-delegation-denied-for-user-email

**Comment by fylyp44** [comment]
Still facing the same error. I have just started to use this package. Any tips?

**Comment by jimhester** [comment]
I think there is a bug when using the magritter chain to construct the
message.  Try building it using the arguments instead and see if it works.

**Comment by fylyp44** [comment]
I have tried that as well. I think the magrittr chain issues is separate.
The function I currently use doesn't use those chains.

Error in send_message(test_email) : client error: (403) Forbidden

This is what I keep getting though...

Thanks for your help.



2015-05-23 17:50 GMT+02:00 Jim Hester <notifications@github.com>:

> I think there is a bug when using the magritter chain to construct the
> message. Try building it using the arguments instead and see if it works.

**Comment by brenoea** [comment]
I  suspect people are facing a scope type error. I sugest to explictly set the scope option when authenticating. For example:

gmail_auth('client.json', scope = 'compose')

**Comment by aashanand** [comment]
Tried brenoea's method and got past this error. 

gmail_auth('client.json', scope = 'compose')

**Comment by jimhester** [comment]
403 Forbidden is due to a scoping error, you need to have at least `scope = 'compose'` to send messages.

**Comment by OmaymaS** [comment]
I am facing a similar error and not sure of the source. Although the authentication is successful and the scope is defined, I get the following errors.

```
gmail_auth(scope = "full", secret_file = "secret.json")

  Waiting for authentication in browser...
  Press Esc/Ctrl + C to abort
  Authentication complete.

mails <- messages(search = "keyword", 10)

  Error in itr(...) : Forbidden (HTTP 403).`
```

```
> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gmailr_0.7.1.9000

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.0  magrittr_1.5    R6_2.2.2        tools_3.4.0     base64enc_0.1-3
 [7] curl_2.6        Rcpp_0.12.12    jsonlite_1.5    httpuv_1.3.3   
```
