### ISSUE TITLE
Support google 'service' applications

### ISSUE THREAD

**Issue by ctbrown** [jimhester/gmailr#13]
It appears that gmailr currently only supports 'installed/native' application. You should:

* state this in the readme file and the vignettes ( I burned a bunch of time trying to figure this out.) 
 
OR 
* also support 'service' application.  It is an easy change and only matters how you parse and send the JSON file.

**Comment by jimhester** [comment]
I tried to make the documentation as clear as possible, if you believe it can be improved please submit a pull request with the changes.

I unfortunately have no idea how to correctly authenticate a service account in an R package. If it is an easy change as you claim and is a feature you are looking for I encourage you to submit a pull request with the improvement.

**Comment by ctbrown** [comment]
Time permitting, I will submit a pull request or just make a fork.  I don't believe this warrants a 'closed' issue, though.  That implies some resolution to the issue; a casual user may think that this is now a feature.  I would recommend leaving it open.

**Comment by jimhester** [comment]
The development version makes authentication much simpler, I did not fully understand google's authentication scheme initially.
