### ISSUE TITLE
messages(...,num_results = 9999) results in too many messages

### ISSUE THREAD

**Issue by jernejkase** [jimhester/gmailr#19]
I thought num_results would just give me all results if the number was greater than the number of matches, but somehow i get exactly the number of results, of course with many duplicate records.

The documentation is sparse, so how exactly is num_results supposed to be used?
Or to put it simply, how can I get all messages in certain label?

**Comment by kazuya030** [comment]
Hi, the master branch seems to have a bug about paging.
I editted about it.
If you can afford, please try 'install_github('kazuya030/gmailr@fixPageToken')'
https://github.com/kazuya030/gmailr/tree/fixPageToken

I have not pulled request it yet, but I will pull request soon.
