### ISSUE TITLE
Parse HTML content from the email

### ISSUE THREAD

**Issue by Btibert3** [jimhester/gmailr#20]
What is the best way to parse out the HTML for an email that includes HTML in the payload?

I am attempting this, but the results are not what I would have expected.

```
email = message(msg_ids[7], format = "full")
email_payload = email$payload
email_text = email_payload$parts[[1]]$body$data
email_html = email_payload$parts[[2]]$body$data
library(RCurl)
email_text_parsed = base64Decode(email_text)
email_html_parsed = base64Decode(email_html)
```
The text parsing appears to work ok, but the HTML doesn't appear to parse properly.

**Comment by jimhester** [comment]
use `body()` with a `type = "text/html"` should do it.

The reason that your approach wasn't working is the emails are [base64 URL encoded](https://en.wikipedia.org/wiki/Base64#URL_applications), not just base64 encoded. See `gmailr:::base64url_decode()`.
