### ISSUE TITLE
Multiple Msgs from Same Thread Not Showing

### ISSUE THREAD

**Issue by cousyman** [jimhester/gmailr#21]
Hi there,

I am attempting to extract multiple e-mails from the same thread. I am using first messages('search query'), then looping through each message_id to extract the body of the message.

When doing this within the same thread of messages, I am only able to open the first message. This first message_id also happens to be the same id as the thread. Coincidence?
Anyway, when I go to extract a message, the one in which I am the only recipient works perfectly.When there are multiple recipients on the list, I am not able to extract the full message. The body of the message is blank.

I believe the issue could be that there are multiple recipients of the e-mail. Am I allowed to extract the data if I am not the only one on the recipients list? 

Thank you!

**Comment by jimhester** [comment]
Could you supply a example response that exhibits this issue?  You can use the `dput()` function in R to dump the data.  You may want to create a fake email thread, or send the example to me via email if it contains information you do not want to be public.
