### ISSUE TITLE
Unable to send mail

### ISSUE THREAD

**Issue by jennybc** [jimhester/gmailr#30]
I've tried everything I know, ranging from creating a new Project (w/ new secret and key) to installing from GitHub and using the built-in defaults. Before I provide a detailed example: are you able to send a test email with `gmailr` these days? I am wondering if it is a transient problem with the Gmail API, although I see no external evidence of that. BTW the "Download JSON" feature is not working in Developers Console right now, although I believe I know how to workaround that.

Using the CRAN version with my own secret and ID, I am getting `Error in send_message(test_email) : client error: (400) Bad Request`. Installling from GitHub and using my own or built-in default credentials, I am getting: `Error: length(url) == 1 is not TRUE`.

Any idea what I'm bumping up against? Do you recommend I use the CRAN version or GitHub version and, if GitHub, which SHA?

**Comment by jimhester** [comment]
The CRAN version should still work fine, I just did the following.

"Download JSON" just worked fine for me (although it is in a different place then before), going to APIs and Auth -> Credentials -> There is a down arrow icon at the right of the screen to download the JSON secret.

Then doing the following worked for me (you should change the email addresses below though) and making both a draft and sending the mail directly worked for me.
```r
m <- mime(To = 'james.f.hester@gmail.com', From = 'james.f.hester@gmail.com', body = 'hi')

create_draft(m)

send_message(m)

m2 <- m %>% html_body("hi2")
create_draft(m2)
```
This is with ` gmailr     * 0.6.0      2014-12-04 CRAN (R 3.3.0)`.

There was a bug in the development code on GitHub when not using https://github.com/gaborcsardi/argufy that was causing the encoding to fail (because the emails were not being converted to characters), which may have been what you were running into.

056d622580f31012a38b685da2edafe61e7338b4 should fix that.

**Comment by jennybc** [comment]
I re-installed from CRAN and was able to successfully download secret/ID as JSON by using Chrome but not Safari. [This stackoverflow thread](http://stackoverflow.com/questions/30894950/client-secret-json-is-empty-upon-download-from-google-developer-site) suggests I am not insane re: the JSON download buttons not necessaril working all the time, on all browsers.

But I still get this with your example above and all of my examples:

```
Error in send_message(m) : client error: (400) Bad Request
```

Do you see anything here that might indicate it's the version of something else?

```
> session_info()
Session info ----------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.2 (2015-08-14)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.700)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Vancouver           
 date     2015-10-06                  

Packages --------------------------------------------------------------------------------
 package    * version    date       source                          
 base64enc    0.1-3      2015-07-28 CRAN (R 3.2.0)                  
 curl         0.9.3      2015-08-25 CRAN (R 3.2.0)                  
 devtools   * 1.9.1.9000 2015-10-01 Github (hadley/devtools@81dd313)
 digest       0.6.8      2014-12-31 CRAN (R 3.2.0)                  
 gmailr     * 0.6.0      2014-12-04 CRAN (R 3.2.0)                  
 httpuv       1.3.3      2015-08-04 CRAN (R 3.2.0)                  
 httr         1.0.0      2015-06-25 CRAN (R 3.2.0)                  
 jsonlite     0.9.17     2015-09-06 CRAN (R 3.2.0)                  
 magrittr     1.5        2014-11-22 CRAN (R 3.2.0)                  
 memoise      0.2.1      2014-04-22 CRAN (R 3.2.0)                  
 R6           2.1.1      2015-08-19 CRAN (R 3.2.0)                  
 Rcpp         0.12.1     2015-09-10 CRAN (R 3.2.0)                  
 reprex     * 0.0.0.9001 2015-09-14 local                           
 rstudioapi   0.3.1      2015-04-07 CRAN (R 3.2.0)                  
 stringi      0.5-5      2015-06-29 CRAN (R 3.2.0)                  
 stringr      1.0.0      2015-04-30 CRAN (R 3.2.0)     
```

Later today I'll revisit installing from GitHub. It is appealing to cut the JSON credentials step out entirely.

**Comment by jimhester** [comment]
Are you setting your scope appropriately to send email?  `gmail_auth(scope
= 'compose')` at least is required in order to do so.

**Comment by jennybc** [comment]
I've even escalated to full at this point. And the OAuth screen has verbiage suggesting I'm using an appropriate scope. Will try harder later today....

**Comment by jimhester** [comment]
Do you get this error only when sending or also when creating drafts?

**Comment by jennybc** [comment]
Only sending

**Comment by jennybc** [comment]
I re-installed from GitHub. Now I get this:

``` r
library(gmailr)
clear_token()
gmail_auth(id = "xxxx.apps.googleusercontent.com",
           secret = "xxxx", scope = "full")
#> Waiting for authentication in browser...
#> Press Esc/Ctrl + C to abort
#> Authentication complete.
m <- mime(To = 'jenny@stat.ubc.ca', From = 'gspreadr@gmail.com', body = 'hi')
create_draft(m)
#> [1] "Id: r-6087211331919750203\nTo: \nFrom: \nDate: \nSubject: \n"
send_message(m)
#> Error: as.character(mail) is not TRUE
session_info("gmailr")
#> Session info --------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.2.2 (2015-08-14)
#>  system   x86_64, darwin13.4.0        
#>  ui       RStudio (0.99.700)          
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/Vancouver           
#>  date     2015-10-06
#> Packages ------------------------------------------------------------------
#>  package   * version date       source                           
#>  base64enc   0.1-3   2015-07-28 CRAN (R 3.2.0)                   
#>  curl        0.9.3   2015-08-25 CRAN (R 3.2.0)                   
#>  digest      0.6.8   2014-12-31 CRAN (R 3.2.0)                   
#>  gmailr    * 0.6.0   2015-10-06 Github (jimhester/gmailr@056d622)
#>  httr        1.0.0   2015-06-25 CRAN (R 3.2.0)                   
#>  jsonlite    0.9.17  2015-09-06 CRAN (R 3.2.0)                   
#>  magrittr    1.5     2014-11-22 CRAN (R 3.2.0)                   
#>  mime        0.4     2015-09-03 CRAN (R 3.2.0)                   
#>  R6          2.1.1   2015-08-19 CRAN (R 3.2.0)                   
#>  stringi     0.5-5   2015-06-29 CRAN (R 3.2.0)                   
#>  stringr     1.0.0   2015-04-30 CRAN (R 3.2.0)
```

It did just occur to me that perhaps the `from` address **must** be a gmail address. Is that true? Because I'm embarrassed to say that's what I've always done in the past, but today I was trying to use my usual email in `from`. I'm about to re-install from CRAN and try again with a gmail `from` address.

**Comment by jimhester** [comment]
Yes the from address has to be an email address associated with your Gmail account.  Otherwise you could spoof email from anyone!

**Comment by jennybc** [comment]
OK I can send again with CRAN version if and only if I put a gmail address in `from`. Perhaps that is supposed to be obvious but sadly slipped by me. Last time I did alot of this I did indeed use a gmail address. However, I think the glitches I'm experiencing with the dev version are actually real.

**Comment by jennybc** [comment]
Update: you do NOT have to provide a Gmail address in `mime(from = ...)`. I just did this and got status 200 and received the email:

``` r
library(gmailr)

# gmail_auth(file.path(PROJHOME, "hw-marking", "stat545-bulk-emailing.json"),
#            'compose')

ret <- send_message(mime(from="jenny@stat.ubc.ca", to="<ANOTHER_EMAIL_I_HAVE>",
                         subject="from is NOT Gmail", body = "body body body"))

httr::status_code(ret)
#> [1] 200
```

Note that I specified my `stat.ubc.ca` email, not Gmail, in `mime()`. I can't tell that the `from =` field even matters, in fact. On the receiving end, the email appears to be from the account associated with the Google Project within which the client ID and secret were obtained.

What seems to be the case is that I succeed when I do the OAuth browser dance when logged in with the account that owns the Google Project/client secret/ID. And I get status `400` otherwise.

Does this make any sense to you? Can you replicate any of it (not sure if you have multiple Google accounts)?

**Comment by jimhester** [comment]
I looked at this again this morning and fixed a number of bugs. The `400` errors were happening because `send_message` was not sending a properly formatted request due to a misunderstanding (on my part) of how jsonlite interprets named vectors.

As far as 'from` emails go, it matters if you have your gmail setup to send from more than one account, however if you enter a from email that is not associated with your gmail account it just sends from your default email.

I have used the same Google Project, secrets ect. with completely unrelated gmail accounts, so they should work regardless of account.

Try installing 4c07595b54ef78a57b68cd62d690aa32daf0d681 and see if it fixes the issues you were having.

**Comment by jennybc** [comment]
My life is dominated by my teaching right now. I need to unleash more email in a couple of days and will return to this then and try out the new version. Will also explore more combinations of who I'm logged in as vs whose ID/secret I'm using and the from address. I have never given any thought to this:

> if you have your gmail setup to send from more than one account

so will look into that.

**Comment by jimhester** [comment]
See https://support.google.com/mail/answer/22370?hl=en for documentation on using the 'Send Mail As:' feature from your gmail.
