### ISSUE TITLE
Provide installation instructions?

### ISSUE THREAD

**Issue by jennybc** [jimhester/gmailr#31]
Right now, to install `gmailr` from GitHub, you must have a very recent version of `devtools` or you get this error:

```
Error: Malformed remote specification 'gaborcsardi/argufy'
```

Maybe until the Remotes feature is present in CRAN `devtools`, you could mention this in the README?

**Comment by jimhester** [comment]
That is only true if you don't attach CRAN devtools first. Run `library(devtools)` first and it works without error on either version.

**Comment by jennybc** [comment]
I think I was in an awkward state re: this where I was not running CRAN devtools but was also not completely current? Does it make sense that there are some intermediate dev versions of devtools that will have this problem?
