### ISSUE TITLE
has_class() should always call is()

### ISSUE THREAD

**Issue by lawremi** [jimhester/gmailr#46]
The `is()` function is the only reliable way to check inheritance in R, because it handles S3/S4 objects _and_ S4 classes. `inherits()` will break for an S3 object tested against, for example, a union of basic classes.

```
> setClassUnion("integerORfactor", c("integer", "factor"))
> inherits(factor(), "integerORfactor")
[1] FALSE
> is(factor(), "integerORfactor")
[1] TRUE
```

Probably can just get rid of `has_class()` and call `is()` directly, because argufy does not do what you want when the assertion is a call.

**Comment by jimhester** [comment]
I think the intent was to avoid loading the methods package.

Maybe a better check would be 

```r
if (isNamespaceLoaded("methods")) {
  methods::is(x, class)
} else {
  inherits(x, class)
}
```

I used that and fixed the calls to actually work with 0ce5c94b6c716b8b2e1ac
