### ISSUE TITLE
as_enum issues

### ISSUE THREAD

**Issue by lawremi** [jimhester/gmailr#49]
There are several functions which use the `as_enum` assertion, which does not resolve the default when the argument is left missing. These include `message()`, `insert_message()`, `import_message()`, `send_message()`, `draft()`, `create_draft()`, and `send_draft()`.

**Comment by jimhester** [comment]
I removed all uses of `as_enum` in favor of `match.arg()` with 6a25439b56981e5922bfc71468560a8a46d23947.

There may be a way to handle this situation properly in argufy but it seems as though we are moving away from using the code annotations anyway so probably not worth the effort.
