### ISSUE TITLE
Attachment

### ISSUE THREAD

**Issue by tmamiya** [jimhester/gmailr#59]
Hello Jim,

Thank you so much for the wondeful package, I have a question:

How do you add attachments to these emails? I have attempted to add it in the mime statement below, however have been unsuccessful. Any direction/help would be Amazing.

test_email <- mime(
To = "tmamiya@walmart.com",
From = "tmamiya.sfs@gmail.com",
Subject = "this is just a gmailr test",
body = "Can you hear me now?")

Thank you!

Todd-

**Comment by jimhester** [comment]
It seems you need to use an html body for it to work properly.
```r
# make an example attachment file
write.csv(iris, "iris.csv")

test_email <- mime(
  To = "tmamiya@walmart.com",
  From = "tmamiya.sfs@gmail.com",
  Subject = "this is just a gmailr test")

# add html body
test_email <- html_body(test_email, "Can you hear me now?")

# attach file to message
test_email <- attach_file(test_email, "iris.csv")

#send message
send_message(test_email)
```

This is using the current code on GitHub, not the CRAN release.

**Comment by tmamiya** [comment]
Awesome that worked!
I uninstalled and installed per github,
Note for those who aren't following the other threads be sure to include the "secret_file ="  attribute otherwise you will have auth issues
gmail_auth(secret_file = "gmailr2.json",scope = 'compose')
Great Work Jim!
