### ISSUE TITLE
send_draft fails in conversion to JSON

### ISSUE THREAD

**Issue by lawremi** [jimhester/gmailr#61]
Attempting to send a draft ends in this error:
```
Error: No method asJSON S3 class: gmail_thread
```

This is because of https://github.com/jimhester/gmailr/blob/master/R/draft.R#L74 which assigns "gmail_thread" to the `message` component of the draft. I think "gmail_thread" implicitly derives from "list", but since that is not made explicit, the `asJSON()` generic fails to dispatch to `asJSON,list()`.

**Comment by lawremi** [comment]
Been a few weeks, so just pinging.  This bug completely breaks `send_draft()`.

**Comment by jimhester** [comment]
Should now be fixed (https://github.com/jimhester/gmailr/commit/6d5bbca384c21b3cccdd206adbd53dde3014016f), thanks for the ping.

**Comment by mvabl-steve** [comment]
I'm having this issue now. The drafts do get posted, but I get this error from R.
