### ISSUE TITLE
gmail_auth is always going to localhost

### ISSUE THREAD

**Issue by sumxf** [jimhester/gmailr#67]
Hello,

I am trying to connect to gmail using gmailr from Rstudio ..

I followed all the steps (like enabling Gmail API, creating Credential, downloading secret file) ..

but when I do gmail_auth .. it finally always takes me to 

http://localhost:1410/?state=5NfJbIBHHk&code=4/e_3mDl_IqYdexUrXvbY_-jZSMvJL5sSgItZJOkFDTPY# and throws error and hangs ..

Best Regards,
Mainak

**Comment by RudyiVT** [comment]
I got the same problem, have you solved it?

**Comment by dcecchini** [comment]
I had the same problem since I was using RStudio Server. I found a solution here:

https://support.rstudio.com/hc/en-us/articles/217952868-Generating-OAuth-tokens-from-a-server

Basically, we can set options(httr_oob_default=TRUE).. Hope it helps

**Comment by jimhester** [comment]
@dcecchini Thanks for the link, that seems the proper solution to this issue.
