### ISSUE TITLE
Change default authentication settings for gmail_auth 

### ISSUE THREAD

**Issue by matt-negrin** [jimhester/gmailr#68]
Hi Jim,

Thanks for your work on this awesome package.

The first time I used gmail_auth, I selected "2", indicating that I would like the package to authenticate in a pop-up window each time it is run. I now would like to run an automated script that uses gmailr from the command line and would like to change my preference to "1" so that no window pops up. Past comments insinuate that I could use a .httr-oauth file to specify my credentials, but I could not find a sample of one nor would I know where I would save it.

Any advice would be greatly appreciated. Thank you!
Matt

**Comment by jimhester** [comment]
The `.httr-oauth` file should be in your R sessions' working directory. You can use `gmailr::clear_token()` to remove it if it already exists, which should prompt you to do the oauth authentication handshake again. You can then copy the new `.httr-oauth` file where needed.

**Comment by matt-negrin** [comment]
Thank you!
