### ISSUE TITLE
Error: oauth_listener() needs an interactive environment.

### ISSUE THREAD

**Issue by songyurita** [jimhester/gmailr#71]
This package works great, but when I was trying to run it via cron, the error throw out. 

Any idea?

Thank you.

**Comment by rluech** [comment]
I have a similar problem, in interactive mode I can send emails but not if the script is run via taskscheduler on windows. I don't get the error but send_mail() keeps on opening the browser for authentification, somehow cant get the oaut info that is present in the interactive session

**Comment by jimhester** [comment]
The credentials are stored in a `.httr-oauth` file in the current working directory by default. So you can place this file wherever the cron job is running and it should then work.

**Comment by rluech** [comment]
Perfect, thanks a lot. `setwd()` to the `.httr-outh` did the job. 
We never change working directory to easier exchange scripts.
`send_message(... , ouath = path)`?

**Comment by jimhester** [comment]
You can set the R option `"httr_oauth_cache"` to wherever you want the oauth cache to live.

`options("httr_oauth_cache" = "/foo/bar/baz")`

**Comment by rluech** [comment]
so good, thanks! works like a breeze :)
